license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="najaewon"
description='''
A post-End progression mod that expands Minecraft with unlockable cities, specialized villagers, player profiles, and private building spaces.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="njw_just_dragon_eggs"
    type="required"
    versionRange="[${just_dragon_eggs_version},)"
    ordering="AFTER"
    side="BOTH"
